version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  helm-tools: pennlabs/helm-tools@0.1.7
  react-tools: pennlabs/react-tools@0.0.2

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - react-tools/check
      - docker/publish:
          requires:
            - react-tools/check
          image: pennlabs/website
          tag: '${CIRCLE_SHA1},latest'
          context: docker-publish
          extra_build_args: '--build-arg GHOST_API_KEY=$GHOST_API_KEY'
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - docker/publish
          context: k8s-deploy
          <<: *branch-filters
